{
 "title": "Capacity Montoring Cluster",
 "tags": [
  "capaticy",
  "custom"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(kube_namespace_labels, namespace)"
   },
   {
    "name": "worker",
    "label": "Nodes",
    "query": "label_values(node_uname_info{job=\"node-exporter\",instance=~\".+:9796\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{nodename=~\"$worker\"}, instance)"
   },
   {
    "name": "kubenode",
    "query": "label_values(kube_pod_info{host_ip=~\"$node\"}, node)"
   }
  ]
 },
 "panels": [
  { "title": "Selected Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage Q95 1w",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1-avg(\n  quantile_over_time(0.95,sum by (instance)(irate(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node.*\",job=~\"node-exporter\"}[5m]))[1w:])\n  /\n  count(node_cpu_seconds_total{mode=\"idle\",instance=~\"$node.*\",job=~\"node-exporter\"}) by (instance)\n)"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(\r\n  sum by(node)(kube_pod_container_resource_requests{node=~\"$kubenode\",resource=\"cpu\",unit=\"core\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\r\n    /\r\n  sum by(node) (kube_node_status_allocatable_cpu_cores{node=~\"$kubenode\"}) \r\n)"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(\r\n  sum by(node)(kube_pod_container_resource_limits{node=~\"$kubenode\",resource=\"cpu\",unit=\"core\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\r\n    /\r\n  sum by(node) (kube_node_status_allocatable_cpu_cores{node=~\"$kubenode\"}) \r\n)"
    }
   ]
  },
  {
   "title": "Memory Utilisation",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "1 - avg(\n  sum by(node) (node_memory_MemAvailable_bytes{instance=~\"$node.*\",job=~\"node-exporter\"})\n  / \n  sum by(node) (node_memory_MemTotal_bytes{instance=~\"$node.*\",job=~\"node-exporter\"})\n)"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(\n  sum by(node) (kube_pod_container_resource_requests{node=~\"$kubenode\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n    / \n  sum by(node) (kube_node_status_allocatable_memory_bytes{node=~\"$kubenode\"})\n)"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "percentunit",
   "valueName": "avg",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(\n  sum by(node) (kube_pod_container_resource_limits{node=~\"$kubenode\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1))\n    / \n  sum by(node) (kube_node_status_allocatable_memory_bytes{node=~\"$kubenode\"})\n)"
    }
   ]
  },
  {
   "title": "Resource Monitoring CPU per Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 }
  },
  {
   "title": "CPU Quota",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",namespace!=\"\",container!=\"\",container!=\"POD\"}[5m])) by (namespace)[1w:])"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",namespace!=\"\",container!=\"\",container!=\"POD\"}[5m])) by (namespace)[1w:])\n/\nsum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"cpu\",unit=\"core\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "quantile_over_time(0.95,sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",namespace!=\"\",container!=\"\",container!=\"POD\"}[5m])) by (namespace)[1w:])\n/\r\nsum(kube_pod_container_resource_limits_cpu_cores{namespace=~\"$namespace\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    }
   ]
  },
  {
   "title": "Resource Monitoring Memory per Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Requests by Namespace",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"\",namespace=~\"$namespace\",container!=\"POD\", job=\"kubelet\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container!=\"\",namespace=~\"$namespace\",container!=\"POD\", job=\"kubelet\"}) by (namespace)\n/\nsum(kube_pod_container_resource_requests{namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{container!=\"\",namespace=~\"$namespace\",container!=\"POD\", job=\"kubelet\"}) by (namespace)\n/\nsum(kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"memory\",unit=\"byte\"} * on(pod, namespace) group_left() (kube_pod_status_phase{phase=\"Running\"}==1)) by (namespace)"
    }
   ]
  }
 ]
}